application: crakseed
version: 1
runtime: go
api_version: go1

handlers:
- url: /html
  static_dir: blogserver/content/

- url: /css
  static_dir: blogserver/content/css/

- url: /images
  static_dir: blogserver/content/images/

- url: /.*
  script: _go_app
